<?php
declare(strict_types=1);

return [
    'MixerApi.JwtAuth' => [

        /*
         * The algorithm you'll use to generate JWTs.
         * - HMAC: HS256 or HS512
         * - RSA: RS256 or RS512
         */
        'alg' => 'RS256',

        /*
         * This is only required if you are using HMAC, it can be left empty otherwise. This can be the value of your
         * applications `Security.salt` or any other string such as something generated by openssl and loaded from
         * your file system with file_get_contents() or from an environment variable.
         */
        'secret' => null, // \Cake\Core\Configure::read('Security.salt'),

        /*
         * An array of public/private key pairs. This can be left empty if you are not using RSA.
         */
        'keys' => [
            [
                /*
                 * The Key ID can be any unique identifier
                 */
                'kid' => '2022-05-01',

                /*
                 * Contents of the public key file
                 */
                'public' => file_get_contents(CONFIG . 'keys' . DS . '1' . DS . 'public.pem'),

                /*
                 * Contents of the private key file
                 */
                'private' => file_get_contents(CONFIG . 'keys' . DS . '1' . DS . 'private.pem'),
            ]
        ]
    ]
];
