<?php

namespace MixerApi\JwtAuth\Test;

use Cake\TestSuite\IntegrationTestTrait;
use Cake\TestSuite\TestCase;
use Firebase\JWT\JWT;
use Firebase\JWT\Key;
use Firebase\JWT\JWK as FirebaseJWK;
use MixerApi\JwtAuth\Configuration\Configuration;
use MixerApi\JwtAuth\Jwk\JwkSet;

class ControllerTest extends TestCase
{
    use IntegrationTestTrait;

    /**
     * @var string[]
     */
    public $fixtures = [
        'plugin.MixerApi/JwtAuth.Users',
    ];

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        static::setAppNamespace('MixerApi\JwtAuth\Test\App');
    }

    public function test_jwks(): void
    {
        TestHelper::createRs256Config();
        $this->get('/test/jwks.json');
        $this->assertResponseOk();
        $body = (string)$this->_response->getBody();
        $result = json_decode($body);
        $this->assertcount(3, $result->keys);
    }

    /**
     * @dataProvider dataProviderForAlg
     * @param string $alg
     * @return void
     */
    public function test_login(string $alg): void
    {
        $alg === 'RS' ? TestHelper::createRs256Config() : TestHelper::createHs256Config();
        $this->post('/test/login.json', ['email' => 'test@example.com', 'password' => 'password']);
        $this->assertResponseCode(200);
        $body = (string)$this->_response->getBody();

        if ($alg === 'RS') {
            $jwt = Jwt::decode($body, FirebaseJWK::parseKeySet((new JwkSet())->getKeySet()), ['RS256']);
        } else {
            $jwt = Jwt::decode($body, new Key((new Configuration)->getSecret(), 'HS256'));
        }

        $this->assertEquals('mixerapi', $jwt->iss);
        $this->assertEquals('test@example.com', $jwt->user->email);
    }

    /**
     * @dataProvider dataProviderForAlg
     * @param string $alg
     * @return void
     */
    public function test_login_fails(string $alg): void
    {
        $alg === 'RS' ? TestHelper::createRs256Config() : TestHelper::createHs256Config();
        $this->post('/test/login.json', ['email' => 'test@example.com', 'password' => 'nope']);
        $this->assertResponseCode(401);
    }

    /**
     * @dataProvider dataProviderForAlg
     * @param string $alg
     * @return void
     */
    public function test_auth_required(string $alg): void
    {
        $alg === 'RS' ? TestHelper::createRs256Config() : TestHelper::createHs256Config();
        $this->get('/test/index.json');
        $this->assertResponseContains('Authentication is required to continue');

    }

    public function dataProviderForAlg(): array
    {
        return [
            ['HS'],['RS']
        ];
    }
}
