<?php

namespace MixerApi\HalView\Test\TestCase\View;

use Cake\Controller\Component\PaginatorComponent;
use Cake\Controller\ComponentRegistry;
use Cake\Controller\Controller;
use Cake\Datasource\FactoryLocator;
use Cake\Datasource\Paging\NumericPaginator;
use Cake\Http\Response;
use Cake\Http\ServerRequest;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\TestSuite\TestCase;

class HalJsonViewTest extends TestCase
{
    /**
     * @var string[]
     */
    public array $fixtures = [
        'plugin.MixerApi/HalView.Actors',
        'plugin.MixerApi/HalView.FilmActors',
        'plugin.MixerApi/HalView.Films',
    ];

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        static::setAppNamespace('MixerApi\HalView\Test\App');
        Router::reload();
        Router::createRouteBuilder('/')->scope('/', function (RouteBuilder $builder) {
            $builder->setExtensions(['json']);
            $builder->connect('/', ['controller' => 'Actors', 'action' => 'index']);
            $builder->connect('/{controller}/{action}/*');
            $builder->connect('/{plugin}/{controller}/{action}/*');
        });
    }

    public function test_item(): void
    {
        $controller = $this->getControllerForItem();

        $controller->viewBuilder()
            ->setClassName('MixerApi/HalView.HalJson')
            ->setOptions(['serialize' => 'actor']);

        $View = $controller->createView();
        $output = $View->render();

        $this->assertIsString($output);

        $object = json_decode($output);

        $this->assertIsObject($object);

        $this->assertEquals('/actors/1', $object->_links->self->href);
        $this->assertIsArray($object->_embedded->films);
    }

    public function test_item_with_no_json_options(): void
    {
        $controller = $this->getControllerForItem();

        $controller->viewBuilder()
            ->setClassName('MixerApi/HalView.HalJson')
            ->setOptions([
                'serialize' => 'actor',
                'jsonOptions' => false,
            ]);

        $View = $controller->createView();
        $output = $View->render();

        $this->assertIsString($output);

        $object = json_decode($output);

        $this->assertIsObject($object);

        $this->assertEquals('/actors/1', $object->_links->self->href);
        $this->assertIsArray($object->_embedded->films);
    }

    private function getControllerForItem(): Controller
    {
        $request = new ServerRequest([
            'url' => 'actors/1',
            'params' => [
                'plugin' => null,
                'controller' => 'Actors',
                'action' => 'view',
                1
            ]
        ]);
        $request = $request->withEnv('HTTP_ACCEPT', 'application/hal+json, text/plain, */*');
        Router::setRequest($request);

        $controller = new Controller($request, new Response());

        $actorTable = FactoryLocator::get('Table')->get('Actors');

        $actor = $actorTable->get(1, contain :['Films']);

        $controller->set([
            'actor' => $actor,
        ]);

        return $controller;
    }
}
