<?php

namespace MixerApi\HalView\Test\TestCase\View;

use Cake\Controller\Component\PaginatorComponent;
use Cake\Controller\ComponentRegistry;
use Cake\Controller\Controller;
use Cake\Datasource\FactoryLocator;
use Cake\Http\Response;
use Cake\Http\ServerRequest;
use Cake\Routing\Router;
use Cake\TestSuite\TestCase;
use MixerApi\Core\Response\ResponseModifier;

class HalJsonViewTest extends TestCase
{
    /**
     * @var string
     */
    private const EXT = 'haljson';

    /**
     * @var string[]
     */
    private const MIME_TYPES = ['application/hal+json','application/vnd.hal+json'];

    /**
     * @var string
     */
    private const VIEW_CLASS = 'MixerApi/HalView.HalJson';

    /**
     * @var string[]
     */
    public $fixtures = [
        'plugin.MixerApi/HalView.Actors',
        'plugin.MixerApi/HalView.FilmActors',
        'plugin.MixerApi/HalView.Films',
    ];

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Router::reload();
        Router::connect('/', ['controller' => 'Actors', 'action' => 'index']);
        Router::connect('/:controller/:action/*');
        Router::connect('/:plugin/:controller/:action/*');
    }

    /**
     * Test Hal Response on a collection (/actors/index)
     */
    public function testHCollection()
    {
        $request = new ServerRequest([
            'url' => 'actors',
            'params' => [
                'plugin' => null,
                'controller' => 'Actors',
                'action' => 'index',
            ]
        ]);
        $request = $request->withEnv('HTTP_ACCEPT', 'application/hal+json, text/plain, */*');
        Router::setRequest($request);
        $response = (new ResponseModifier(self::EXT, self::MIME_TYPES, self::VIEW_CLASS))
            ->modify($request, new Response());

        $controller = new Controller($request, $response, 'Actors');
        $controller->modelClass = 'Actors';
        $registry = new ComponentRegistry($controller);

        $paginator = new PaginatorComponent($registry);

        $actorTable = FactoryLocator::get('Table')->get('Actors');
        $actors = $paginator->paginate($actorTable, [
            'contain' => ['Films'],
            'limit' => 1
        ]);

        $controller->set([
            'actors' => $actors,
        ]);

        $controller->viewBuilder()
            ->setClassName('MixerApi/HalView.HalJson')
            ->setOptions(['serialize' => 'actors']);
        $View = $controller->createView();
        $output = $View->render();

        $this->assertIsString($output);

        $object = json_decode($output);

        $this->assertIsObject($object);

        $this->assertEquals(1, $object->count);
        $this->assertEquals(20, $object->total);
        $this->assertEquals('/actors', $object->_links->self->href);
        $this->assertEquals('/?page=2', $object->_links->next->href);
        $this->assertEquals('/?page=20', $object->_links->last->href);

        $actor = $object->_embedded->actors[0];

        $this->assertIsArray($actor->_embedded->films);
        $this->assertEquals('/actors/1', $actor->_links->self->href);
    }

    /**
     * Test Hal Response on a item (/actors/view)
     */
    public function testItem()
    {
        $request = new ServerRequest([
            'url' => 'actors/1',
            'params' => [
                'plugin' => null,
                'controller' => 'Actors',
                'action' => 'view',
                1
            ]
        ]);
        $request = $request->withEnv('HTTP_ACCEPT', 'application/hal+json, text/plain, */*');
        Router::setRequest($request);
        $response = (new ResponseModifier(self::EXT, self::MIME_TYPES, self::VIEW_CLASS))
            ->modify($request, new Response());

        $controller = new Controller($request, $response, 'Actors');
        $controller->modelClass = 'Actors';

        $actorTable = FactoryLocator::get('Table')->get('Actors');

        $actor = $actorTable->get(1, [
            'contain' => ['Films'],
        ]);

        $controller->set([
            'actor' => $actor,
        ]);

        $controller->viewBuilder()
            ->setClassName('MixerApi/HalView.HalJson')
            ->setOptions(['serialize' => 'actor']);

        $View = $controller->createView();
        $output = $View->render();

        $this->assertIsString($output);

        $object = json_decode($output);

        $this->assertIsObject($object);

        $this->assertEquals('/actors/1', $object->_links->self->href);
        $this->assertIsArray($object->_embedded->films);
    }
}