name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ ubuntu-18.04 ]
        php-versions: ['7.3', '7.4', '8.0']

    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, sqlite3, json, xml, simplexml, mysqli
          tools: composer:v2
          coverage: xdebug

      - name: Matrix PHP Version
        run: |
          echo ${{ matrix.php-versions }}
          php -v

      - name: Composer Check
        run: |
          composer check
          composer validate

      - name: Install
        run: composer install --prefer-dist --no-interaction --no-progress --no-suggest

      - name: Test Project
        run: |
          cp config/.env.example config/.env
          cp config/app_local.example.php config/app_local.php
          composer test

      - if: ${{ matrix.php-versions }} == '7.4'
        name: Upload coverage results to Coveralls (7.4 only)
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${{ matrix.php-versions }}
          export CODECOVERAGE=1 && vendor/bin/phpunit --verbose --coverage-clover=clover.xml
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=clover.xml -v

  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - if: github.ref == 'refs/heads/master'
        name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: mixerapi.com
          username: ${{ secrets.MIXERAPI_COM_USER}}
          key: ${{ secrets.MIXERAPI_COM_PRIVATE_KEY}}
          script: ${{ secrets.MIXERAPI_COM_DEPLOY_CMD}}
