name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ ubuntu-18.04 ]
        php-versions: ['7.3', '7.4', '8.0']

    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl

      - name: Matrix PHP Version
        run: echo ${{ matrix.php-versions }}

      - name: Installed PHP Version
        run: php -v

      - name: Install
        run: composer install

      - if: ${{ matrix.php-versions }} != '7.4'
        name: Test Project
        run: |
          cp config/.env.example config/.env
          composer test

      #- if: ${{ matrix.php-versions }} == '7.4'
      #  name: Test + Code Quality (7.4 only)
      #  run: make check

  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: mixerapi.com
          username: ${{ secrets.MIXERAPI_COM_USER}}
          key: ${{ secrets.MIXERAPI_COM_PRIVATE_KEY}}
          script: ${{ secrets.MIXERAPI_COM_DEPLOY_CMD}}
