name: Pull Request

on:
  pull_request:

jobs:
  build:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.3']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, sqlite3, xml, simplexml, mysqli
          tools: composer:v2

      - name: Matrix PHP Version
        run: |
          echo ${{ matrix.php-versions }}
          php -v

      - name: Composer Check
        run: composer validate

      - name: Install
        run: |
          composer install --prefer-dist --no-interaction --no-progress
          composer update
          cp config/.env.example config/.env
          cp config/app_local.example.php config/app_local.php

      - name: Test Suite + Static Analysis
        if: ${{ matrix.php-versions}}
        run: |
          composer analyze

  coverage:
    name: PHP ${{ matrix.php-versions }} w/ Coverage Report
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, sqlite3, xml, simplexml, mysqli
          tools: composer:v2
          coverage: xdebug

      - name: Composer Check
        run: composer validate

      - name: Install
        run: |
          composer install --prefer-dist --no-interaction --no-progress
          composer update
          cp config/.env.example config/.env
          cp config/app_local.example.php config/app_local.php

      - name: Coverage Report
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          export CODECOVERAGE=1 && vendor/bin/phpunit --coverage-clover=clover.xml
          php-coveralls --coverage_clover=clover.xml -v

  #
  # Test plugins individually
  #
  plugins:
    name: ${{ matrix.plugin }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        plugin: [
          'bake',
          'core',
          'collection-view',
          'crud',
          'exception-render',
          'hal-view',
          'json-ld-view',
          'jwt-auth'
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, sqlite3, xml, simplexml, mysqli

      - name: PHP Version
        run: php -v

      - name: ${{matrix.plugin}} tests
        run: |
          cp config/.env.example config/.env
          cp plugins/${{matrix.plugin}}/composer.json .
          rm -rf composer.lock
          composer install
          vendor/bin/phpunit plugins/${{matrix.plugin}}
