name: Pull Request

on:
  pull_request:
    branches: [ master, 0.next, v1.x ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ ubuntu-18.04 ]
        php-versions: ['8.0']

    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, sqlite3, xml, simplexml, mysqli
          tools: composer:v2
          coverage: xdebug

      - name: Matrix PHP Version
        run: |
          echo ${{ matrix.php-versions }}
          php -v

      - name: Composer Check
        run: composer validate

      - name: Install
        run: |
          composer install --prefer-dist --no-interaction --no-progress
          cp config/.env.example config/.env
          cp config/app_local.example.php config/app_local.php

      #- name: Unit Tests (7.3|8.0)
      #  if: ${{ matrix.php-versions != '7.4' }}
      #  run: |
      #    composer test

      - name: Static Analysis + Coveralls
        #if: ${{ matrix.php-versions == '7.4' }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer analyze
          echo ${{ matrix.php-versions }}
          export CODECOVERAGE=1 && vendor/bin/phpunit --verbose --coverage-clover=clover.xml
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=clover.xml -v

  #
  # CakePHP version compatability
  #
  compatibility:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['~4.2.0', '~4.3.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, intl, sqlite3, xml, simplexml, mysqli

      - name: PHP Version
        run: php -v

      - name: CakePHP ${{matrix.version}} Compatability
        run: |
          cp config/.env.example config/.env
          composer self-update
          rm -rf composer.lock
          composer require cakephp/cakephp:${{matrix.version}} --no-update
          composer install --prefer-dist --no-progress
          composer test
